### ISSUE TITLE
Toolset directory for version '14.38' was not found.

### ISSUE THREAD

**Issue by MisterDA** [ilammy/msvc-dev-cmd#80]
Starting today (2024-05-16), the action has started failing. Any idea of what's happening?

```yaml
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.38
          arch: ${{ matrix.x86_64 && 'x64' || 'x86' }}
```

```
Found with vswhere: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
Error: Could not setup Developer Command Prompt: invalid parameters
[ERROR:vcvars.bat] Toolset directory for version '14.38' was not found.
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
```

**Comment by pzhlkj6612** [comment]
Hi!

As per [[Windows-2022] Multiple VC Build Tools will be removed on May, 13 · Issue #9701 · actions/runner-images](https://github.com/actions/runner-images/issues/9701), I think GitHub has removed all VC++ toolsets except the latest one (for now it's 14.39). That's why the version 14.38 was not found.

Please compare the following two files (lines highlighted by me; I have no idea why two 14.29 toolsets are preserved):

- [20240421.1 Windows2022-Readme.md](https://github.com/actions/runner-images/blob/win22/20240421.1/images/windows/Windows2022-Readme.md?plain=1#L366-L461)
- [20240514.3 Windows2022-Readme.md](https://github.com/actions/runner-images/blob/win22/20240514.3/images/windows/Windows2022-Readme.md?plain=1#L366-L399)

.

**Comment by MisterDA** [comment]
That what I finally figured, thanks! It's strange though, I thought that 14.39 was pre-release. The page at [Latest Microsoft Visual C++ Redistributable Version](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version) still indicates 14.38.

If I don't specify `toolset`, will vcvarsall default to the latest version?

Thanks for the help!

**Comment by binarymaster** [comment]
Looks related: https://github.com/actions/runner-images/issues/9701

**Comment by pzhlkj6612** [comment]
@MisterDA 

> If I don't specify `toolset`, will vcvarsall default to the latest version?

The `toolset` parameter is actually the `-vcvars_ver` parameter of "vcvarsall"[^1]. Microsoft says that "_By default, the environment is set to use the current Visual Studio compiler toolset_"[^2], and there should be only one toolset on GitHub-hosted runners[^3], so I think you will pick the latest version by omitting the `toolset` parameter.

[^1]: [lib.js#L156-L158](https://github.com/ilammy/msvc-dev-cmd/blob/0b201ec74fa43914dc39ae48a89fd1d8cb592756/lib.js#L156-L158).
[^2]: [`vcvarsall` syntax § Use the Microsoft C++ toolset from the command line | Microsoft Learn](https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line#vcvarsall-syntax).
[^3]: [Using GitHub-hosted runners - GitHub Docs](https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners).

**Comment by MisterDA** [comment]
Thanks a lot!
