### ISSUE TITLE
error MSB8020: The build tools for v144 (Platform Toolset = 'v144') cannot be found.

### ISSUE THREAD

**Issue by PeakRacing** [ilammy/msvc-dev-cmd#82]
![image](https://github.com/ilammy/msvc-dev-cmd/assets/24759100/0785be6a-a288-4293-8e89-2edd35a93f11)

https://github.com/Dozingfiretruck/nes/actions/runs/9425160319/job/25967261426

**Comment by pzhlkj6612** [comment]
Hi!

The only installed VC++ toolset on GitHub is the latest one (for now is v14.40 [^1]). Since your "Set up MSVC" step did not fail, I think xmake should find the toolset correctly. You may check those posts in xmake's repository:

- https://github.com/xmake-io/xmake/issues/4772
- https://github.com/xmake-io/xmake/pull/4800
- https://github.com/xmake-io/xmake/pull/5176

If everything looks normally but your workflow still does not work, you could try raising an issue in xmake repo (don't forget to link this issue).

[^1]: [20240603.1 Windows2022-Readme.md](https://github.com/actions/runner-images/blob/win22/20240603.1/images/windows/Windows2022-Readme.md?plain=1#L470-L480)

**Comment by PeakRacing** [comment]
OK，thanks
